name: flutter_cached
description: "ðŸ§¾ Flutter widget allowing cache-based data display featuring swipe-to-refresh and an error banner."
version: 5.0.1
homepage: https://github.com/marcelgarus/flutter_cached

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  maybe: ^0.4.0
  meta: ^1.1.7
  pull_to_refresh: ^1.5.6
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
